// 1️⃣ Import the Poppins font from Google Fonts in Next.js
import { Poppins } from "next/font/google";

// 2️⃣ Import global styles
import "./globals.css";

// 3️⃣ Initialize the Poppins font with desired settings
const poppins = Poppins({
  variable: "--font-poppins", // CSS variable for the font
  subsets: ["latin"],  // Include Latin character set
  weight: ["100", "200", "400", "700", "900"], // Specify font weights (normal & bold)
});

// 4️⃣ Metadata for SEO and page description
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 5️⃣ RootLayout Component - Wraps the entire application
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Apply the Poppins font using the CSS variable */}
      <body className={`${poppins.variable}`}>{children}</body>
    </html>
  );
}
